-- CAD SaaS MVP Supabase Schema Definition
-- Generated by Kodari dba-expert

-- 1. Profiles Table (User Data)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email TEXT UNIQUE,
  company_name TEXT,
  -- SP2/A-5: 결제 게이트웨이 런타임 사용 컬럼 (app/services/payment.py)
  plan_type TEXT NOT NULL DEFAULT 'free' CHECK (plan_type IN ('free', 'single', 'basic', 'pro')),
  credits INTEGER NOT NULL DEFAULT 0 CHECK (credits >= 0),
  stripe_subscription_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Users can view their own profile
CREATE POLICY "Users can view own profile" 
ON public.profiles FOR SELECT 
USING (auth.uid() = id);

-- Users can update their own profile
CREATE POLICY "Users can update own profile" 
ON public.profiles FOR UPDATE 
USING (auth.uid() = id);

-- Trigger for new user profile creation
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (NEW.id, NEW.email);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user();

-- 2. Projects Table (Tracks CAD conversion tasks)
CREATE TABLE IF NOT EXISTS public.projects (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  original_filename TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'error')),
  ifc_url TEXT,
  error_message TEXT,
  -- SP2/A-5: 인시던트·컴플라이언스 소견 등 확장 메타데이터 저장 (endpoints.py)
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- SP2/A-5: 기존 배포 환경용 멱등 마이그레이션 (신규 설치는 CREATE TABLE에 이미 반영됨)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS plan_type TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS credits INTEGER;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS stripe_subscription_id TEXT;
UPDATE public.profiles SET plan_type = 'free' WHERE plan_type IS NULL;
UPDATE public.profiles SET credits = 0 WHERE credits IS NULL;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS metadata JSONB;

-- Enable RLS
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- Users can view their own projects
CREATE POLICY "Users can view own projects" 
ON public.projects FOR SELECT 
USING (auth.uid() = user_id);

-- Users can insert their own projects
CREATE POLICY "Users can insert own projects" 
ON public.projects FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Users can update their own projects (or Service Role via backend)
CREATE POLICY "Users can update own projects" 
ON public.projects FOR UPDATE 
USING (auth.uid() = user_id);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_profiles
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_updated_at_projects
BEFORE UPDATE ON public.projects
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();
